project:
  type: website
  output-dir: docs

website:
  title: "**Yuanxu Dong, PhD**<br>Humboldt Fellowship for Postdoc"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: cosmo
    toc: false
