project:
  type: website
  output-dir: docs

website:
  title: "**Yuanxu Dong**, Humboldt Fellowship for Postdoc"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: CV
        href: cv.qmd
    right:
      - icon: google
        href: https://scholar.google.com/citations?user=X1tSc9IAAAAJ&hl=en
      - icon: envelope
        href: mailto:ydong@geomar.de

format:
  html:
    theme: cosmo
    toc: false
