project:
  type: website
  output-dir: docs

website:
  title: "**Yuanxu Dong, PhD**<br>Humboldt postdoc fellowship"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Bio
        href: Bio.qmd
      - text: Publications
        href: publications.qmd
      - text: Resources
        href: Resources.qmd

format:
  html:
    theme: flatly
    css: styles.css
    html-extensions: true